name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Prepare
        run: |
          npm install
          npm run ci:check
          npm run ci:build
          cp dist/rta/browser/{index,404}.html

      - name: Upload build artifacts
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/rta/browser/

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
